### ISSUE TITLE
Redirect to blank page

### ISSUE THREAD

**Issue by asingh532** [payu-intrepos/PayUMoney-Android-SDK#1]
After pressing Pay Button its redirect to a blank page. How to resolve it?

**Comment by vinayakmestri** [comment]
I have implemented PayU SDK, once i complete the transaction it redirects to success url. however when i press back button it shows message "Do you really want to cancel the transaction". i have successfully done my payment then when i press back button then it should redirect to the app directly.

**Comment by Rahul-Hooda** [comment]
Closing this issue due to no active discussions. If still issue exists, please write to us at mobile.integration@payu.in
