### ISSUE TITLE
Shows Alert for Payment Cancellation. Even after successful transaction.

### ISSUE THREAD

**Issue by vinayakmestri** [payu-intrepos/PayUMoney-Android-SDK#2]
![screenshot_2016-08-21-13-47-49](https://cloud.githubusercontent.com/assets/7300823/17836174/55f53ee4-67a6-11e6-9d9a-0aeda823114f.png)
I have implemented PayUSDK. I have done my transaction successfully. However after successful transaction it redirects to success url and when i press back button (Android). it shows alert "Do you really want to cancel the transaction". This alert should not shows when transaction is completed and user on success page url. please resolve this or give me any solution if you have. I have shared image for reference. it is success page url. and when i press back button it shows alert.

**Comment by Rahul-Hooda** [comment]
Closing this issue due to no active discussions. If still issue exists, please write to us at mobile.integration@payu.in
