### ISSUE TITLE
Whole SDK is an issue :(

### ISSUE THREAD

**Issue by chillaxdev** [payu-intrepos/PayUMoney-Android-SDK#3]
Hello,

As per the details provided here,
https://www.payumoney.com/dev-guide/mobilecheckout/android.html

I have done everything and when I landed on the payment gateway it asked me to log in. After I logged in, the screen looks like below. I have tried reinstalling and clearing caches. It also showed "Some error occurred! Try again" using the Toast API.

### Stack trace

> V/FA: Activity paused, time: 339468
> V/FA: onActivityCreated
> V/FA: Activity resumed, time: 339610
> D/OpenGLRenderer: endAllActiveAnimators on 0x8f1e5e00 (InsetDrawable) with handle 0x8dd0d0c0
> E/Volley: [235] BasicNetwork.performRequest: Unexpected response code 401 for https://test.payumoney.com/auth/app/setUserPaymentOption
> E/PayUMoneySdk: Session...new JsonHttpResponseHandler() {...}.onFailure: null
> W/System: Ignoring header UserSessionCookiePageUrl because its value was null.
> I/Difference: [ main: SdkSession.java: 520: onResponse() ] --> URL=/payment/op/getNetBankingStatusTime=68
> E/Volley: [237] BasicNetwork.performRequest: Unexpected response code 401 for https://test.payumoney.com/payment/app/payment/addSdkPayment
> E/PayUMoneySdk: Session...new JsonHttpResponseHandler() {...}.onFailure: null
> W/System: Ignoring header UserSessionCookiePageUrl because its value was null.
> W/IInputConnectionWrapper: finishComposingText on inactive InputConnection
> I/Difference: [ main: SdkSession.java: 520: onResponse() ] --> URL=/auth/app/op/merchant/LoginParams?merchantId=5808093Time=281
> V/FA: Activity paused, time: 340372
> V/FA: onActivityCreated
> V/FA: Activity resumed, time: 340412
> I/Difference: [ main: SdkSession.java: 520: onResponse() ] --> URL=/auth/app/op/merchant/LoginParams?merchantId=5808093Time=402
> W/IInputConnectionWrapper: finishComposingText on inactive InputConnection
> I/Difference: [ main: SdkSession.java: 520: onResponse() ] --> URL=/auth/oauth/tokenTime=362
> V/FA: Activity paused, time: 351931
> V/FA: Activity resumed, time: 351957
> I/Difference: [ main: SdkSession.java: 520: onResponse() ] --> URL=/auth/app/setUserPaymentOptionTime=197
> I/Difference: [ main: SdkSession.java: 520: onResponse() ] --> URL=/payment/op/getNetBankingStatusTime=228
> 06-04 03:23:49.568 3806-3806/ I/Difference: [ main: SdkSession.java: 520: onResponse() ] --> URL=/payment/app/payment/addSdkPaymentTime=229
> 06-04 03:23:49.602 3806-3806/ W/IInputConnectionWrapper: finishComposingText on inactive InputConnection
> 

**PS: How do I skip the login/signup screen and directly pay with the credit/debit/net banking? :)**

Thank You

![screenshot_1496519705](https://cloud.githubusercontent.com/assets/25753366/26757230/82adca3c-48d3-11e7-9871-22414517d822.png)

**Comment by jagjotsinghparry** [comment]
I have the same issue with no luck here. Did you find anything about it?

**Comment by chillaxdev** [comment]
No bro. It's more than a month and still no response from them.

**Comment by cears-bhumika** [comment]
+1
Same issue for me too :-1:

**Comment by jagjotsinghparry** [comment]
I've managed to resolve this issue. I'll write you up a solution by the day's end. Or you can book a technical call from PayUMoney and they'll tell you to refer to this repository for the correct code :smile:

The key is to use the code in this repository for testing this SDK and when they approve your account use the live credentials they give you.

**Comment by cears-bhumika** [comment]
I've arrange technical call but If any workaround will help more
Its request you to provide your solution too..

Thanks in advance

**Comment by akuma34** [comment]
We are having same issue,  is there anyone who can tell the solution here?

**Comment by chillaxdev** [comment]
@firangistan It didn't work even for a sandbox payment. But thanks for your help. I'll try calling them 👍

**Comment by Shvet** [comment]
Anyone have solved problem? I can run test credential but my own key and salt and merchant id is not working.

**Comment by jagjotsinghparry** [comment]
@Shvet check if the hash generating code is correct or if the account is active :smile:

**Comment by MNGsulochana** [comment]
Hi,Actually still I am facing this issue "some error occured",In my side if it is the problem with the merchant key ,my old Application with the Pay u money SDK is working,Right now I am trying to implementing by using dependency (latest ) in android side ..

MY json object response is
josnobject: {"status":0,"result":"e21b449e413a0e90e24fa7eca2aff010bb19b15f45ddbdf01654f7e17f38b05f0b8f059e84d2217dd503d1d6a9cc9edf02ff8c6025048008352c091e68bf4b7a","errorCode":null,"responseCode":null}

this JSON response id for SANDBOX ,even for SANDBOX also I am getting this issue
For SANDBOX in onactivityResult I am getting ....../MainActivity: request code 10000 resultcode 0
For PRODUCTION also in onactivityResult I am getting ....../MainActivity: request code 10000 resultcode 0

Please ,help me out..by using latest dependency,I am facing this issue
But my Old pay u money sdk is wokring fine with all the merchant details
Please help me what was the issue exactly

**Comment by chetnajaiswal7862083** [comment]
@chillaxdev  I also faced same issue recently. Its working for me now. Can you please share your code so that I can suggest you anything.

**Comment by adnanganie** [comment]
I am getting this error "Some error occurred", I tried to contact the support team on the website, but they have not responded yet

**Comment by Rahul-Hooda** [comment]
@adnanganie - Please drop a mail to mobile.integration@payu.in with below integration details-
1. PayUmoney SDK version 
2. Video of replicating the issue
3. Error logs, if any
4. Your integration code

**Comment by Rahul-Hooda** [comment]
Closing this issue due to no active discussions. If still issue exists, please write to us at mobile.integration@payu.in
