### ISSUE TITLE
"Some error occurred" on init 

### ISSUE THREAD

**Issue by harshitaahuja** [payu-intrepos/PayUMoney-Android-SDK#4]
`WebViewFactory: Loading com.android.chrome version 63.0.3239.111 (code 323911102)
12-23 16:09:00.886 31584-31584/? I/cr_LibraryLoader: Time to load native libraries: 4 ms (timestamps 4623-4627)
12-23 16:09:00.898 31584-31584/? I/chromium: [INFO:library_loader_hooks.cc(36)] Chromium logging enabled: level = 0, default verbosity = 0
12-23 16:09:00.898 31584-31584/? I/cr_LibraryLoader: Expected native library version number "63.0.3239.111", actual native library version number "63.0.3239.111"
12-23 16:09:00.921 31584-31584/? I/cr_BrowserStartup: Initializing chromium process, singleProcess=true
12-23 16:09:00.982 31584-31584/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.eb>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/webkit/RenderProcessGoneDetail;
12-23 16:09:00.982 31584-31584/? I/art:     at com.android.webview.chromium.Ap com.android.webview.chromium.WebViewChromiumFactoryProvider.G(android.webkit.WebView, android.content.Context) (WebViewChromiumFactoryProvider.java:325)
12-23 16:09:00.982 31584-31584/? I/art:     at void com.android.webview.chromium.WebViewChromium.init(java.util.Map, boolean) (WebViewChromium.java:42)
12-23 16:09:00.982 31584-31584/? I/art:     at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int, int, java.util.Map, boolean) (WebView.java:636)
12-23 16:09:00.982 31584-31584/? I/art:     at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int, int) (WebView.java:572)
12-23 16:09:00.982 31584-31584/? I/art:     at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int) (WebView.java:555)
12-23 16:09:00.982 31584-31584/? I/art:     at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet) (WebView.java:542)
12-23 16:09:00.982 31584-31584/? I/art:     at void android.webkit.WebView.<init>(android.content.Context) (WebView.java:532)
12-23 16:09:00.982 31584-31584/? I/art:     at java.lang.String com.payumoney.core.utils.AnalyticsHelper.getUserAgent(android.content.Context) (AnalyticsHelper.java:46)
12-23 16:09:00.982 31584-31584/? I/art:     at void com.payumoney.core.utils.SdkHelper.deviceAnalytics(android.content.Context, com.payumoney.core.PayUmoneySdkInitializer$PaymentParam) (SdkHelper.java:578)
12-23 16:09:00.982 31584-31584/? I/art:     at com.payumoney.core.PayUmoneySDK com.payumoney.core.PayUmoneySDK.init(android.content.Context, com.payumoney.core.PayUmoneySdkInitializer$PaymentParam) (PayUmoneySDK.java:45)
12-23 16:09:00.982 31584-31584/? I/art:     at void com.payumoney.sdkui.ui.utils.PayUmoneyFlowManager.startPayUMoneyFlow(com.payumoney.core.PayUmoneySdkInitializer$PaymentParam, android.app.Activity, int, boolean) (PayUmoneyFlowManager.java:38)`

**Comment by harshitaahuja** [comment]
@Override
    public void onFailureResponse(ErrorResponse response, String tag) {
        mProgressDialog.dismiss();
        Toast.makeText(context, "Some error occured", Toast.LENGTH_SHORT).show();
        finish();
    }

this method in PayUmoneyActivity does not show error from errorresponse. just the general error. which is very problematic to debug.

**Comment by sanidhya09** [comment]
Same error for me. Did you get any solution?

**Comment by aktinfotech** [comment]
can any one please let me know the issue

**Comment by Rahul-Hooda** [comment]
Closing this issue due to no active discussions. If still issue exists, please write to us at mobile.integration@payu.in
