### ISSUE TITLE
Issues occured in release build after android Lollipop version

### ISSUE THREAD

**Issue by tmsundaram-android** [payu-intrepos/PayUMoney-Android-SDK#5]
Unable to resume activity {payumoney.payu.com.payumoneysdkapp/com.payUMoney.sdk.SdkHomeActivityNew}: a.a.a.d: Subscriber class com.payUMoney.sdk.SdkHomeActivityNew has no public methods called onEvent

This error will occurred only in Release build of this Sample app from android marshmallow to current android version(oreo).

**Comment by Rahul-Hooda** [comment]
Closing this issue due to no active discussions. If still issue exists, please write to us at mobile.integration@payu.in
