### ISSUE TITLE
Android pie issue while processing payment request

### ISSUE THREAD

**Issue by priteshc** [payu-intrepos/PayUMoney-Android-SDK#7]
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.payumoney.core.PayUmoneySDK.addPayment(com.payumoney.core.listener.OnPaymentOptionReceivedListener, java.lang.String)' on a null object reference

**Comment by Huzefa-Infiswift** [comment]
I had same issue I fixed it using the webview approach.. so whenever you detect a device with higher or equal OS version then Android PIE go for webview approach

**Comment by hardz** [comment]
I have solved by this thing 

Put this in the Manifest: under the application tag
`<uses-library android:name="org.apache.http.legacy" android:required="false"/>`

**Comment by priteshc** [comment]
i have solved this issue 
 <uses-library
            android:name="org.apache.http.legacy"
            android:required="false" />

put this code in your manifest application tag

**Comment by ghost** [comment]
Hello !! What put in manifest application tag ?

**Comment by priteshc** [comment]
<uses-library
            android:name="org.apache.http.legacy"
            android:required="false"/>

**Comment by priteshc** [comment]
uses-library
            android:name="org.apache.http.legacy"
            android:required="false"

**Comment by saecmca** [comment]
I tried this but not working
Put this in the Manifest: under the application tag

   '<uses-library android:name="org.apache.http.legacy" android:required="false"/>'

any other alternate solutions?

**Comment by saecmca** [comment]
> I have solved by this thing
> 
> Put this in the Manifest: under the application tag
> `<uses-library android:name="org.apache.http.legacy" android:required="false"/>`

not working for me

**Comment by Rahul-Hooda** [comment]
Closing this issue due to no active discussions. If still issue exists, please write to us at mobile.integration@payu.in

**Comment by Mayank1904** [comment]
Attempt to invoke virtual method 'void com.payumoney.core.PayUmoneySDK.addPayment(com.payumoney.core.listener.OnPaymentOptionReceivedListener, java.lang.String)' on a null object reference
